cat("foo\tbar", fill = TRUE)
cat("foo\nbar", fill = TRUE)
cat("foo\0bar", fill = TRUE)
cat("foo\\bar", fill = TRUE)
cat("foo'bar", fill = TRUE)
cat("foo\"bar", fill = TRUE)
cat('foo\'bar', fill = TRUE)
cat("foo'bar", fill = TRUE)
cat('foo"bar', fill = TRUE)
cat("\a")
alarm()
